# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo:4.4.3-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - /data/db

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  rest-api:
    build:
      context: ./plaeto-backend
      dockerfile: Dockerfile-rest-api
    image: plaeto-rest-api
    ports: 
      - 8000:8000

  socket-server:
    build:
      context: ./plaeto-backend
      dockerfile: Dockerfile-socket-server
    image: plaeto-socket-server
    ports:
      - 5000:5000

  web-client:
    build: ./plaeto-frontend
    image: plaeto-web-client
    ports:
      - 8080:8080