FROM python:3

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY util/requirements.txt ./

# install project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY main.py .

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host" ,"0.0.0.0"]