FROM python:3

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY util/requirements.txt ./

# install project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY plaeto_project/ .

EXPOSE 5000
CMD ["gunicorn", "-k", "eventlet", "-w", "1", "socketsapp.wsgi:app", "--bind", "0.0.0.0:5000"]